### ISSUE TITLE
expo-constants error in bundling

### ISSUE THREAD

**Issue by peyman-hakemi** [jeanverster/react-native-styled-toast#13]
i get this error after installing react-native-styled-toast in my bundling.

> bundling failed: Error: Unable to resolve module `expo-constants` from `node_modules\react-native-styled-toast\dist\Context\index.js`: expo-constants could not be found within the project.

my project created by react native cli: react-native init and i not using expo.
is there any way that i can use this library in my react-native project without expo?
@jeanverster

**Comment by jeanverster** [comment]
Hi @peyman-hakemi, according to the Expo docs you are able to install the `expo-constants` module in a bare react native app - you can follow the instructions below:

https://github.com/expo/expo/tree/master/packages/expo-constants#installation-in-bare-react-native-projects

Let me know if that helps 👍

**Comment by RochaMoran** [comment]
Try Updating packages to the latest version.

`npm update`

give a try to install with `--force` flag as well if the update has not worked. eg:
`npm install --force`
