### ISSUE TITLE
Optionally hide icon in toast

### ISSUE THREAD

**Issue by hrmoller** [jeanverster/react-native-styled-toast#16]
It would be nice if it was possible to optionally hide the icon shown left of the message.

![Untitled](https://user-images.githubusercontent.com/645472/77952029-4c2a7580-72cb-11ea-830d-1b1a9c477b4c.png)

**Comment by jeanverster** [comment]
Hi @hrmoller that sounds like a good idea, will implement 👍

**Comment by jeanverster** [comment]
@hrmoller this is now possible using the `hideIcon` prop in the latest version :) Also, you can now customize the icon to your needs using any icon family from `react-native-vector-icons` 🎉
