### ISSUE TITLE
Is Expo Constants Really Necessary?

### ISSUE THREAD

**Issue by kkkasio** [jeanverster/react-native-styled-toast#17]
Hello .. Good night!
First of all thanks for your work, the package is really incredible.
I spent a few hours selecting some toast component for RN, and I came across your work, I thank you and found it incredible!

However, I come humbly to ask why I depend on the expo's constants!
is there anything we can do to reverse this situation?

For people who are not at the expo, it is a tremendous bureaucracy to install some expo packages out of it!

REF: https://github.com/expo/expo/tree/master/packages/expo-constants

**Comment by jeanverster** [comment]
Hi @kkkasio, apologies for only getting back to you now. I haven't had much time to have a look at / maintain this library but trying to get around to the issues now! So I've had a look and it seems that this might actually be a good solution: https://www.npmjs.com/package/react-native-status-bar-height

The only reason I was using expo constants was for getting the status bar height, and with the above package it seems like I would be able to get it without having to rely on `expo-constants`. I will make the change soon and submit a new version 👍

**Comment by jeanverster** [comment]
@kkkasio I have removed the `expo-constants` dependency in the latest version :)

**Comment by kkkasio** [comment]
Hello my friend, sorry I didn't answer earlier.

Your work as I said is incredible for this package.
I am very grateful for giving some attention to this PR, in the project that I am in, I was not able to use your package, but I will use it next time!

Thank you very much <3
