### ISSUE TITLE
Warning - Expected style "borderWidth: 1" to contain units

### ISSUE THREAD

**Issue by arturchyzy** [jeanverster/react-native-styled-toast#19]
When running i get this warning `Expected style "borderWidth: 1" to contain units`

`border-width` property in `styles.tsx`is missing units like `px` or sth.

**Comment by jeanverster** [comment]
Hi @arturchyzy yes sorry I think this is because SC v5 started enforcing explicitly using `px` in the values. I will update 👍

**Comment by jeanverster** [comment]
fixed in #23
