### ISSUE TITLE
Error: Unable to resolve module `styled-components/native` 

### ISSUE THREAD

**Issue by reactnative103** [jeanverster/react-native-styled-toast#26]
Hi @jonoirwinrsa & @jonoirwinrsa ,

Can you please help with the below error?

Error:
Unable to resolve module `styled-components/native` from `node_modules/react-native-styled-toast/dist/Box/index.js`: styled-components/native could not be found within the project.

"react": "^16.13.1",
"react-native": "^0.63.2",

Thanks & regards,

**Comment by jonoirwinrsa** [comment]
@reactnative103 do you have styled-components installed?

**Comment by reactnative103** [comment]
@jonoirwinrsa : Thanks for your quick reply.

Appreciated this great library. Fabulous work guys.
Got it your point. May be have mentioned in the document. If not so please add it.

Thanks again.

**Comment by vahdet** [comment]
Indeed, the library should have `styled-components` as a dependency itself. I saw it in [`package.json`](package.json) as a `peerDependecy` and is not installed automatically (at least on my local with npm v6.14.9). Would you consider moving the library to `dependencies` section maybe?
