### ISSUE TITLE
Limit the number of visible toasts.

### ISSUE THREAD

**Issue by JanKaifer** [jeanverster/react-native-styled-toast#39]
Hi, sometimes there is too much going on, and the user can be overwhelmed by too many toast notifications.
It proved to be useful to limit the max number of displayed notifications to a fixed number (like `3` on mobile).
When there were more toasts than allowed, other toasts could wait until the first ones are closed, or they could force close them.

Anyway love this project <3

**Comment by jeanverster** [comment]
Hi @JanKaifer will have a look at implementing this 👍
