### ISSUE TITLE
Allow styling of Toast and custom icons

### ISSUE THREAD

**Issue by pke** [jeanverster/react-native-styled-toast#40]
Thanks for the library. I wonder if there is an easy way to further style the toasts like changing their border radius? Could this be achieved via theming?

Furthermore could the lib support custom icons handed in as React components?

**Comment by centosix** [comment]
solve it ?

**Comment by jeanverster** [comment]
Hi @pke - thanks for this, it definitely seems possible, I think one solution could also be to pass your own Toast component to replace the one provided, that way you would be able to customize the UI completely.. Will look into providing both options :)

**Comment by dmlux** [comment]
Well, it seems that there are more extensive options for styling the toast, but what about custom icons? In my current project, an external designer has created his own icons and graphics, which are completely incompatible with the provided fonts in this project. I also need to add icons to the header of the toast, which is also currently not possible. Another problem I currently have with this library is that while I can change the icon, I am not allowed to change the styling of its wrapping container. I think a better solution would be to allow something like `<ToastProvider position="BOTTOM" toastComponent={MyCustomToastComponent}/>`. If you need listeners for actions like close, etc, you could provide an interface for properties that custom components need to implement. This solution would allow developers to also add custom action listeners to toasts to do other things like send requests when buttons are pressed, etc.
