### ISSUE TITLE
Toast behaves strangely on tap

### ISSUE THREAD

**Issue by dmlux** [jeanverster/react-native-styled-toast#55]
Hi, 

first, thank you for your library!

I have noticed that toasts behave strangely when a user taps directly on them rather than the close button. The tapped toast gets smaller and its distance from the bottom of the screen decreases. Is there any way to turn off this behavior? If the toast is an error toast, it does not disappear automatically and therefore it is more difficult to press the close button on the smaller version of the toast.

**Comment by bsheikh** [comment]
Hey @dmlux; have you had any lucky resolving this issue? Experiencing the same issue

**Comment by jeanverster** [comment]
Hi @dmlux @bsheikh could you guys please try update to the latest version and see if the issue persists? :)

**Comment by dmoebius** [comment]
Hi, I'm a colleague of @dmlux and I can confirm that this issue is fixed in the latest release 1.3.0. Many thanks!! :)

**Comment by dmlux** [comment]
Hi, sorry for the late response. The issue seems to be resolved, thanks! :-)
