### ISSUE TITLE
hideCloseIcon default won't override to true

### ISSUE THREAD

**Issue by mjlkerr** [jeanverster/react-native-styled-toast#60]
When I try to override the hideCloseIcon and set it to true it doesn't work for me.  I cloned the repo and set it to default to true and it works and overrides as expected.

**Comment by jeanverster** [comment]
Hi @mjlkerr I've tested on my side and am not able to reproduce the issue 🤔 Could you perhaps share some code so I can have a look at your implementation? Also could you perhaps try updating to the latest version and see if that resolves the issue?

**Comment by mjlkerr** [comment]
@jeanverster thanks for the reply, I updated the package and all is well now 👍 

Unfortunately I think I'm still going to have to fork because I need to add custom images to these toasts.
